### PR TITLE
Adding vertical aligmment to fixed grid column

### LINKED ISSUE #113: Support vertical centering on FixedGridColumn

### PR DESCRIPTION
**Pull request by rahultiru**
Adding vertical align prop to the FixedGridColumn component. Fixes #113 

## Pull request checklist

* [x] Component `README.md` file is up-to-date.
* [x] Component visual reference files are up-to-date.
* [x] Component is unit tested.

### CODE REVIEW

File: src/components/FixedGrid/FixedGridColumn.tsx [hunk 1]
```diff
@@ -15,6 +15,12 @@ export interface FixedGridColumnProps extends NestableBaseComponentProps {
    * The number of pixels wide this column should be. Ignored if `fixed` is not set to true.
   */
   width?: number;
+
+  /**
+   * The vertical alignment of the column's content
```
Comment (unindented) [inline src/components/FixedGrid/FixedGridColumn.tsx]: This sentence should end with a period.

Comment (swese44) [reply src/components/FixedGrid/FixedGridColumn.tsx]: can we add a linter to enforce that?

Comment (unindented) [reply src/components/FixedGrid/FixedGridColumn.tsx]: It'd be nice, but I don't know of a rule that'd do this. We'll have to rely on people looking at other descriptions and trying to keep things consistent.
